/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JAX.WS.SOAP;

import JAX.WS.SOAP.api.EstoqueWS;

import javax.xml.ws.Endpoint;

public class App {
    public static void main(String[] args) {

        EstoqueWS implementacaoWS = new EstoqueWS();
        String URL = "http://localhost:8080/estoquews";

        System.out.println("EstoqueWS rodando: " + URL);

        //associando URL com implementacao
        Endpoint.publish(URL, implementacaoWS);

    }
}
