version: '3.4'
services:

  mariadb:
    image: mariadb:10.3.15
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: spring-cloud-store-db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - backend
    restart: always
    volumes:
      - ./mariadb:/var/lib/mysql

networks:
  backend:
    driver: bridge