server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tiagobmarques/alura
          search-paths: spring-cloud-registry-config-server/config-server/config/supplier